---
apiVersion: v1
kind: Secret
metadata:
  name: blues-man-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/WindTurbineInc/blues-man-gateway-gitops
